### ISSUE TITLE
Incorrect use of validation

### ISSUE THREAD

**Issue by VladMomotov** [KatiaSychik/my_blog#2]
https://github.com/KatiaSychik/my_blog/blob/fdceb698998469e62821cf460790c125eb1771c9/app/models/user.rb#L8

вроде как [presence](https://guides.rubyonrails.org/active_record_validations.html#presence) делает тоже самое

**Comment by KatiaSychik** [comment]
я гэта брала з сайта рельсаў:

Так как false.blank? это true, если хотите провести валидацию существования булева поля, нужно использовать одну из следующих валидаций:
validates :boolean_field_name, inclusion: { in: [true, false] }
validates :boolean_field_name, exclusion: { in: [nil] }

**Comment by VladMomotov** [comment]
не подумал об этом, спасибо)
