### ISSUE TITLE
Посты принадлежащие активным пользователям

### ISSUE THREAD

**Issue by VladMomotov** [KatiaSychik/my_blog#3]
https://github.com/KatiaSychik/my_blog/blob/fdceb698998469e62821cf460790c125eb1771c9/test/models/console_testing.rb#L9

Попробуй использовать джойн

**Comment by KatiaSychik** [comment]
https://github.com/KatiaSychik/my_blog/commit/0f69146e2a3f6bb0f92c53364a2ec58ebc4abae6
