### ISSUE TITLE
Вывести только посты с статусом inactive, under_review.

### ISSUE THREAD

**Issue by VladMomotov** [KatiaSychik/my_blog#4]
https://github.com/KatiaSychik/my_blog/blob/fdceb698998469e62821cf460790c125eb1771c9/test/models/console_testing.rb#L18

Передавай хэш в `.where`

**Comment by VladMomotov** [comment]
И отрефактори остальные запросы тоже. Везде где возможно стоит использовать передавать хэш вместо строки

**Comment by KatiaSychik** [comment]
https://github.com/KatiaSychik/my_blog/commit/b01fc6c546dc3ee853f11903ae86d03981f0ccbc
