### ISSUE TITLE
Обновление поста

### ISSUE THREAD

**Issue by VladMomotov** [KatiaSychik/my_blog#5]
https://github.com/KatiaSychik/my_blog/blob/fdceb698998469e62821cf460790c125eb1771c9/test/models/console_testing.rb#L24

все ок, но обычно просто вот так делают:

```
post.update(status: 'active')
```

**Comment by KatiaSychik** [comment]
выправіла https://github.com/KatiaSychik/my_blog/blob/master/spec/models/console_testing.rb
